# embed_resources.cmake
# Generates EmbeddedResources.h/.cpp from a manifest of resource files.
#
# Usage (from add_custom_command):
#   cmake -DMANIFEST=/path/to/manifest.txt -DOUTPUT_DIR=/path/to/generated -P embed_resources.cmake
#
# The manifest file lists one resource file path per line.
# Each input file becomes a const std::string_view in namespace egiamp::resources.
# Symbol names are derived from filenames: lowercase, spaces/hyphens/dots become underscores,
# leading "HydroCel_GSN_" and "GSN_HydroCel_" prefixes are stripped, trailing version suffixes removed.

# Read manifest
file(STRINGS "${MANIFEST}" RESOURCE_FILES)

# Collect all declarations and definitions
set(DECLARATIONS "")
set(DEFINITIONS "")

foreach(RESOURCE_FILE ${RESOURCE_FILES})
    # Read file content
    file(READ "${RESOURCE_FILE}" FILE_CONTENT)

    # Derive symbol name from filename
    get_filename_component(BASENAME "${RESOURCE_FILE}" NAME_WE)

    # Normalize: lowercase, replace spaces/hyphens/dots with underscores
    string(TOLOWER "${BASENAME}" SYMBOL)
    string(REPLACE " " "_" SYMBOL "${SYMBOL}")
    string(REPLACE "-" "_" SYMBOL "${SYMBOL}")
    string(REPLACE "." "_" SYMBOL "${SYMBOL}")

    # Strip common prefixes
    string(REGEX REPLACE "^hydrocel_gsn_" "" SYMBOL "${SYMBOL}")
    string(REGEX REPLACE "^gsn_hydrocel_" "" SYMBOL "${SYMBOL}")

    # Strip trailing version remnant (e.g. "_1" from "32_1" after NAME_WE)
    string(REGEX REPLACE "_[0-9]+$" "" SYMBOL "${SYMBOL}")

    # Prefix: "tiling_" for XML files, "montage_" for .sfp files
    if(RESOURCE_FILE MATCHES "\\.xml$")
        set(SYMBOL "tiling_${SYMBOL}")
    elseif(RESOURCE_FILE MATCHES "\\.sfp$")
        set(SYMBOL "montage_${SYMBOL}")
    endif()

    # Build declaration
    string(APPEND DECLARATIONS "extern const std::string_view ${SYMBOL};\n")

    # Build definition with raw string literal
    # Use a delimiter unlikely to appear in the data
    string(APPEND DEFINITIONS "const std::string_view ${SYMBOL} = R\"__RES__(${FILE_CONTENT})__RES__\";\n\n")
endforeach()

# Generate header
file(WRITE "${OUTPUT_DIR}/egiamp/EmbeddedResources.h"
"// Auto-generated by embed_resources.cmake — do not edit
#ifndef EGIAMP_EMBEDDEDRESOURCES_H
#define EGIAMP_EMBEDDEDRESOURCES_H

#include <string_view>

namespace egiamp::resources {

${DECLARATIONS}
} // namespace egiamp::resources

#endif // EGIAMP_EMBEDDEDRESOURCES_H
")

# Generate source
file(WRITE "${OUTPUT_DIR}/EmbeddedResources.cpp"
"// Auto-generated by embed_resources.cmake — do not edit
#include \"egiamp/EmbeddedResources.h\"

namespace egiamp::resources {

${DEFINITIONS}
} // namespace egiamp::resources
")
