# generate_filter_delays.cmake
# Generates egiamp/FilterDelays.h from resources/sampling_rates.json.
#
# Usage (from add_custom_command):
#   cmake -DJSON_FILE=/path/to/sampling_rates.json -DOUTPUT_DIR=/path/to/generated \
#         -P generate_filter_delays.cmake
#
# The JSON is the single source of truth for the EEG anti-alias filter delays
# used to compensate decimated-mode timestamps. For each amplifier the
# `eeg_shift_msec` object maps a rate key -> delay in milliseconds. A key
# suffixed "_fast_recovery" (e.g. "1000_fast_recovery") describes the native
# fast-recovery variant of that rate. Values equal samples at source_rate
# (1000 Hz), which is why they are milliseconds.
#
# Each rate entry becomes one row in a constexpr table keyed by
# (AmplifierType, sampleRate, fastRecovery). Only amplifiers named exactly as
# the AmplifierType enumerators (NA300 / NA400 / NA410) are emitted; a new key
# in the JSON that has no matching enumerator will fail to compile — fail fast.

file(READ "${JSON_FILE}" JSON_CONTENT)

set(ROWS "")

string(JSON AMP_COUNT LENGTH "${JSON_CONTENT}" amplifiers)
if(AMP_COUNT GREATER 0)
    math(EXPR AMP_LAST "${AMP_COUNT} - 1")
    foreach(ai RANGE 0 ${AMP_LAST})
        string(JSON AMP_KEY MEMBER "${JSON_CONTENT}" amplifiers ${ai})

        string(JSON EEG GET "${JSON_CONTENT}" amplifiers "${AMP_KEY}" eeg_shift_msec)
        string(JSON RATE_COUNT LENGTH "${EEG}")
        if(NOT RATE_COUNT GREATER 0)
            continue()
        endif()

        math(EXPR RATE_LAST "${RATE_COUNT} - 1")
        foreach(ri RANGE 0 ${RATE_LAST})
            string(JSON RATE_KEY MEMBER "${EEG}" ${ri})
            string(JSON MS GET "${EEG}" "${RATE_KEY}")

            if(RATE_KEY MATCHES "_fast_recovery$")
                string(REPLACE "_fast_recovery" "" RATE "${RATE_KEY}")
                set(FAST_RECOVERY "true")
            else()
                set(RATE "${RATE_KEY}")
                set(FAST_RECOVERY "false")
            endif()

            string(APPEND ROWS
                "    {AmplifierType::${AMP_KEY}, ${RATE}, ${FAST_RECOVERY}, ${MS}},\n")
        endforeach()
    endforeach()
endif()

file(WRITE "${OUTPUT_DIR}/egiamp/FilterDelays.h"
"// Auto-generated by generate_filter_delays.cmake — do not edit.
// Source of truth: resources/sampling_rates.json
#ifndef EGIAMP_FILTERDELAYS_H
#define EGIAMP_FILTERDELAYS_H

#include \"egiamp/AmpServerProtocol.h\"

namespace egiamp::filterdelays {

struct FilterDelayEntry {
    AmplifierType type;
    int sampleRate;
    bool fastRecovery;
    int eegDelayMs;  // EEG anti-alias (FPGA) filter delay, milliseconds
};

// One row per amplifier x rate (x fast-recovery). Generated from
// eeg_shift_msec in sampling_rates.json.
inline constexpr FilterDelayEntry kFilterDelays[] = {
${ROWS}};

// EEG anti-alias filter delay in milliseconds for the given amplifier, sample
// rate, and fast-recovery (native) flag. Returns 0 when no matching entry
// exists — native rates, fast recovery, or an unknown amp/rate — i.e. no
// FPGA filter and therefore no delay to compensate.
inline int eegFilterDelayMs(AmplifierType type, int sampleRate, bool fastRecovery) {
    for (const auto& e : kFilterDelays) {
        if (e.type == type && e.sampleRate == sampleRate && e.fastRecovery == fastRecovery) {
            return e.eegDelayMs;
        }
    }
    return 0;
}

} // namespace egiamp::filterdelays

#endif // EGIAMP_FILTERDELAYS_H
")
